# Generated by Django 2.2.17 on 2021-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210214_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Client',
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
